language: node_js
node_js: stable

install:
  - npm install

script:
  - hexo g 

after_script:
  - 'sed -i "s/GH_TOKEN/${GH_TOKEN}/" _config.yml'
  - hexo d

branches:
  only:
    - demo

cache:
  directories:
    - node_modules
